export const countryList = [
   'Afghanistan',
   'Albania',
   'Algeria',
   'American Samoa',
   'Andorra',
   'Angola',
   'Anguilla',
   'Antarctica',
   'Antigua & Barbuda',
   'Argentina',
   'Armenia',
   'Aruba',
   'Australia',
   'Austria',
   'Azerbaijan',
   'Bahamas',
   'Bahrain',
   'Bangladesh',
   'Barbados',
   'Belarus',
   'Belgium',
   'Belize',
   'Benin',
   'Bermuda',
   'Bhutan',
   'Bolivia',
   'Bosnia',
   'Botswana',
   'Bouvet Island',
   'Brazil',
   'Brunei',
   'Bulgaria',
   'Burkina Faso',
   'Burundi',
   'Cambodia',
   'Cameroon',
   'Canada',
   'Cape Verde',
   'Cayman Islands',
   'Central African Republic',
   'Chad',
   'Chile',
   'China',
   'Christmas Island',
   'Cocos Islands',
   'Colombia',
   'Comoros',
   'Congo',
   'Dem. Rep. Congo',
   'Cook Islands',
   'Costa Rica',
   "Cote D'Ivoire",
   'Croatia',
   'Cuba',
   'Cyprus',
   'Czech Republic',
   'Denmark',
   'Djibouti',
   'Dominica',
   'Dominican Republic',
   'Ecuador',
   'Egypt',
   'El Salvador',
   'Equatorial Guinea',
   'Eritrea',
   'Estonia',
   'Ethiopia',
   'Malvinas',
   'Faroe Islands',
   'Fiji',
   'Finland',
   'France',
   'French Guiana',
   'French Polynesia',
   'French S. Terr.',
   'Gabon',
   'Gambia',
   'Georgia',
   'Germany',
   'Ghana',
   'Gibraltar',
   'Greece',
   'Greenland',
   'Grenada',
   'Guadeloupe',
   'Guam',
   'Guatemala',
   'Guernsey',
   'Guinea',
   'Guinea-Bissau',
   'Guyana',
   'Haiti',
   'Heard Island & Mcdonald Islands',
   'Vatican City State',
   'Honduras',
   'Hong Kong',
   'Hungary',
   'Iceland',
   'India',
   'Indonesia',
   'Iran',
   'Iraq',
   'Ireland',
   'Isle of Man',
   'Israel',
   'Italy',
   'Jamaica',
   'Japan',
   'Jersey',
   'Jordan',
   'Kazakhstan',
   'Kenya',
   'Kiribati',
   'N. Korea',
   'S. Korea',
   'Kuwait',
   'Kyrgyzstan',
   'Laos',
   'Latvia',
   'Lebanon',
   'Lesotho',
   'Liberia',
   'Libya',
   'Liechtenstein',
   'Lithuania',
   'Luxembourg',
   'Macao',
   'Macedonia',
   'Madagascar',
   'Malawi',
   'Malaysia',
   'Maldives',
   'Mali',
   'Malta',
   'Marshall Islands',
   'Martinique',
   'Mauritania',
   'Mauritius',
   'Mayotte',
   'Mexico',
   'Micronesia',
   'Moldova',
   'Monaco',
   'Mongolia',
   'Montserrat',
   'Morocco',
   'Mozambique',
   'Myanmar',
   'Namibia',
   'Nauru',
   'Nepal',
   'Netherlands',
   'New Caledonia',
   'New Zealand',
   'Nicaragua',
   'Niger',
   'Nigeria',
   'Niue',
   'Norfolk Island',
   'Northern Mariana Islands',
   'Norway',
   'Oman',
   'Pakistan',
   'Palau',
   'Palestine',
   'Panama',
   'Papua New Guinea',
   'Paraguay',
   'Peru',
   'Philippines',
   'Pitcairn',
   'Poland',
   'Portugal',
   'Puerto Rico',
   'Qatar',
   'Reunion',
   'Romania',
   'Russia',
   'Rwanda',
   'Saint Helena',
   'Saint Kitts & Nevis',
   'Saint Lucia',
   'St. Pierre & Miquelon',
   'Saint Vincent',
   'Samoa',
   'San Marino',
   'Sao Tome & Principe',
   'Saudi Arabia',
   'Senegal',
   'Serbia & Montenegro',
   'Seychelles',
   'Sierra Leone',
   'Singapore',
   'Slovakia',
   'Slovenia',
   'Solomon Islands',
   'Somalia',
   'South Africa',
   'South Georgia',
   'Spain',
   'Sri Lanka',
   'Sudan',
   'Surilabel',
   'Svalbard',
   'Swaziland',
   'Sweden',
   'Switzerland',
   'Syria',
   'Taiwan',
   'Tajikistan',
   'Tanzania',
   'Thailand',
   'Timor-Leste',
   'Togo',
   'Tokelau',
   'Tonga',
   'Trinidad & Tobago',
   'Tunisia',
   'Turkey',
   'Turkmenistan',
   'Turks & Caicos',
   'Tuvalu',
   'Uganda',
   'Ukraine',
   'United Arab Emirates',
   'United Kingdom',
   'United States',
   'Uruguay',
   'Uzbekistan',
   'Vanuatu',
   'Venezuela',
   'Viet Nam',
   'Virgin Islands, British',
   'Virgin Islands, U.S.',
   'Wallis & Futuna',
   'Western Sahara',
   'Yemen',
   'Zambia',
   'Zimbabwe',
];
